test failure: getting signer via sync
Error message:

  thread 'tests::keys::async_agent_signature' panicked at 'Cannot
  start a runtime from within a runtime. This happens because a
  function (like `block_on`) attempted to block the current thread
  while the thread is being used to drive asynchronous tasks.'